"""Update channel model with additional fields

Revision ID: 7096919a99ce
Revises: f3d30d28e8c4
Create Date: 2025-07-28 10:30:31.361419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7096919a99ce'
down_revision: Union[str, Sequence[str], None] = 'f3d30d28e8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('custom_url', sa.String(length=255), nullable=True))
    op.add_column('channels', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('channels', sa.Column('published_at', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'published_at')
    op.drop_column('channels', 'view_count')
    op.drop_column('channels', 'custom_url')
    # ### end Alembic commands ###
