"""Add additional YouTube channel fields

Revision ID: f3d30d28e8c4
Revises: c461b8bb3e3f
Create Date: 2025-07-28 09:57:05.353198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d30d28e8c4'
down_revision: Union[str, Sequence[str], None] = 'c461b8bb3e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
